version: v1
plugins:
  - name: openapiv2
    out: api
    opt:
      - logtostderr=true
      - allow_merge=true
      - merge_file_name=openapi
      - json_names_for_fields=true
      - output_format=yaml
      - disable_service_tags=true